esphome:
  name: test-sonoff
  platform: ESP8266
  board: esp8285

wifi:
  ssid: "changeme"
  password: "changeme"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "changeme"
    password: "changeme"

# Enable Home Assistant API    
api:

# Enable logging
logger:

ota:
  password: "changeme"
  
captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
